# Standard Ruby and Rails RuboCop configuration
require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.9
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/routes.rb'

# Relaxed rules for prototype development
Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
